### PR TITLE
Reset current attempt stats after match

### LINKED ISSUE #24: Reset start time for limit != 1
When multiple keys are generated, the number of attempts is reset but the start time is not. Thus the speed output is incorrect after the 1st key found.

```
$ ./target/debug/nano-vanity --limit 4 .sim
Estimated attempts needed: 32768
Tried 9981 keys (~30.46%; 1197.5 keys/s)
Found matching account!
Private Key: 5EDC2C45744F0596E7FD59F90DD14B6DE41C6DBB8F193EEF9F28DC3B82702310
Address:     xrb_3simaai9g1gobbwktuzgoaxtc5sq31efe4mc381f3cg549ym9mnaacu5fkmp
Tried 8090 keys (~24.69%; 552.0 keys/s)
Found matching account!
Private Key: D92639C14EFDF98BBACC51255F23045880EFA55D5CAF2A273D971C52E7F78307
Address:     xrb_3simfjfi9fou8noyjyys3e7k3ffi5c9wzyc849jog4ix116qbsyhskkz1gof
Tried 54848 keys (~167.38%; 916.3 keys/s)
Found matching account!
Private Key: ACEDB623ACDED9A5F9847DD975DB78F6F510F7BF22739B86C15F7360A62389EB
Address:     xrb_1simeuyr1njemhkuz38mhnrerrcyft4ud6jg8oiii4umbj63ferusocacxss
Tried 7213 keys (~22.01%; 109.4 keys/s)
Found matching account!
Private Key: 98BD1DD8E87CF5E59BE1A2254BA1AA4C3BEDB040D512D3F65C053E78D0F6B90B
Address:     xrb_1sim7jd8k7jjtqng131jabdhdmhcz31do4kbe9ar9pnnksejzzpfahw9xye5
```

I'll work on a PR.

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #24

### CODE REVIEW

**Comment by PlasmaPower** [comment]
When both reading and writing 0, the attempts counter should be accessed inside of the start time mutex, to avoid race conditions. That said, have you considered just not resetting the attempts counter? It makes sense to me if at the 3rd key progress is 300%. It'd give you an overall progress vs an individual progress.

**Comment by webmaster128** [comment]
> When both reading and writing 0, the attempts counter should be accessed inside of the start time mutex, to avoid race conditions.

I considered the case showing (attempts, start_time) where one is reset and the other is not for 250 milliseconds irrelevant. If you want to go that far and push for correctnes, we should have a struct (attempts, start_time) that is protected by a single RwLock. 

> That said, have you considered just not resetting the attempts counter? It makes sense to me if at the 3rd key progress is 300%. It'd give you an overall progress vs an individual progress.

I don't know if I understand correctly. All stats (estimated, keys, ratio, speed) are currently based on the current attempt and changing this is probably out of scope. Personally I have no interest in other limits than 1 and unlimted, in which case the overall progress makes no sense.

**Comment by webmaster128** [comment]
Just let me know which way you prefer. I'm fine with both

**Comment by PlasmaPower** [comment]
I'd prefer not resetting the attempts counter. I don't think there's a significant difference for the user, so let's stick with what makes the code simpler.

**Comment by webmaster128** [comment]
Here we go: #26

**Pull request closed without merging**
