### PR TITLE
optional Apple OpenCL support +  global_work_size argument

### PR DESCRIPTION
**Pull request by brandonros**
part of https://github.com/PlasmaPower/nano-vanity/issues/59

### CODE REVIEW

**Comment by brandonros** [comment]
@PlasmaPower any guesses?

```
Brandons-Laptop:nano-vanity brandon 2024-04-16 12:29:44 $ cargo run -- --threads 0 --gpu xrb_3xem
   Compiling nano-vanity v0.4.14 (/Users/brandon/Desktop/nano-vanity)
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `/Users/brandon/.cargo/target/debug/nano-vanity --threads 0 --gpu xrb_3xem`
Estimated attempts needed: 65536
Initializing GPU Apple Apple M3
UNSUPPORTED (log once): createKernel: newComputePipelineState failed
thread 'main' panicked at src/main.rs:406:10:
called `Result::unwrap()` on an `Err` value: OclCore(Api(

################################ OPENCL ERROR ############################### 

Error executing function: clCreateKernel("generate_pubkey")  

Status error code: CL_INVALID_KERNEL (-48)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateKernel.html#errors  

############################################################################# 
))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Brandons-Laptop:nano-vanity brandon 2024-04-16 12:30:15 $ 
```

**Comment by PlasmaPower** [comment]
I'm not sure, OpenCL compat is a mess. When I was still working on this project actively I was trying tons of alternatives, though I didn't find any without their own serious issues at the time. SPIR-V might be in better shape now. That looked the most promising.

I'd be worried that by merging this change we'd break NVIDIA GPUs again. Another contributor PR'd the __generic tags to fix NVIDIA. Maybe you could use conditional compilation, but personally I'd consider just renting an NVIDIA GPU in the cloud instead (no guarantees that'll work though).

**Comment by brandonros** [comment]
Thanks for the reply. Working through the code...

https://github.com/PlasmaPower/nano-vanity/blob/0ffe066c49a420ac1219cdb29630922ef4d24082/src/opencl/blake2b.cl#L271

This is crashing the OpenCL compiler...

I'll try to see if I can get it to work.

**Comment by brandonros** [comment]
Converting it to a macro fixes the issue *shrug*

```
$ cargo run -- --threads 0 --gpu xrb_3xxxxx
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `/Users/brandon/.cargo/target/debug/nano-vanity --threads 0 --gpu xrb_3xxxxx`
Estimated attempts needed: 67108864
Initializing GPU Apple Apple M3
Tried 32505856 keys (~48.44%; 2658313.4 keys/s)
Found matching account!
Private Key: redacted
Address:     nano_3xxxxx4cg56fuhc6jcxibrb8e44qn9838ueu9b3c7dyha38g9dyjdbgs7w53
```

**Review by PlasmaPower — APPROVED** [review]
LGTM

**Comment by brandonros** [comment]
@PlasmaPower thanks, sorry, I had it as draft, if you could merge please now, thank you!!!

**Pull request merged**
