### PR TITLE
Cleanup OCL dependency

### PR DESCRIPTION
**Pull request by webmaster128**
* Remove outdated direct dependency ocl-core
* Update ocl to 0.19.1 (because we can)

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I'm afraid to merge this because I've heard reports of nano-work-server not working on MacOS, at least partially because of its newer ocl version (I have an old-ocl branch there for testing).

**Comment by webmaster128** [comment]
In a fork of this project, I happily use ocl 0.19.1.

But what about just merging the 1st commit? This is a harmless cleanup. Feel free to checkky pick onto master and close the rest.

**Comment by PlasmaPower** [comment]
I just merged the first commit. I'll keep this PR open though, because we definitely should upgrade ocl. I'm just not sure it's worth the risk right now.

**Comment by webmaster128** [comment]
Arlright. At the moment I have no specific reason for the upgrade. So it can idle around a bit.

**Comment by webmaster128** [comment]
Closing as 0.19.2 is out now

**Pull request closed without merging**
